Pull request #38: Mdnhossa/lumberjack
Merge in NETAUTO/lvv-service from mdnhossa/lumberjack to master

Squashed commit of the following:

commit 23a065fa5ed8c629192b0b6730fe88d7c98ea7a5
Author: Md Nahid Hossain <md.nahid.hossain@oracle.com>
Date:   Thu Jun 6 12:06:19 2024 -0400

    final lumberjack changes

commit 46ffc142614b3c15722a42ea2072ee182c4f8318
Author: Md Nahid Hossain <md.nahid.hossain@oracle.com>
Date:   Thu Jun 6 10:23:37 2024 -0400

    run file update

commit 5467006423058cd64cb62e67303f278785eeeed3
Author: Md Nahid Hossain <md.nahid.hossain@oracle.com>
Date:   Wed Jun 5 16:40:12 2024 -0400

    update file count

commit 05e7600b99ce2ed89a2762583fa128dee9855003
Author: Md Nahid Hossain <md.nahid.hossain@oracle.com>
Date:   Wed Jun 5 15:32:00 2024 -0400

    file count

commit 7410b3dc912b6284fd70b009d810093f66599f6e
Author: Md Nahid Hossain <md.nahid.hossain@oracle.com>
Date:   Wed Jun 5 15:30:38 2024 -0400

    file count

commit df032386911b0bb5c9e952f74a930f565fc22f22
Author: Md Nahid Hossain <md.nahid.hossain@oracle.com>
Date:   Wed Jun 5 12:15:45 2024 -0400

    deploying chainsaw script

diff --git a/lvv-service-api/docker/etc/sv/chainsaw/run b/lvv-service-api/docker/etc/sv/chainsaw/run
--- a/lvv-service-api/docker/etc/sv/chainsaw/run
+++ b/lvv-service-api/docker/etc/sv/chainsaw/run
@@ -1,13 +1,27 @@
 #!/bin/bash
 exec 2>&1
 
+
 # =============================================================================
 # Launch Chainsaw2
 # =============================================================================
+echo "Launching Chainsaw \n"
 
-# Todo-Replace: Replace with your compartmentId and lumberjack namespace here.
-chainsaw2 \
-    --compartment="ocid1.compartment.oc1..aaaaaaaa26mceal7cypzsefhbm2l73xtb3yreplacemereplacemereplaceme" \
-    --namespace="lvv-service-api" \
-    --s2sbyinstanceprincipal \
-    --metrics="{\"projectName\"=\"lvv-service\",\"fleetName\"=\"lvv-service-api\"}"
+# Check for for odo manifest file. If present we are in a cloud machine.
+
+ODO_MANIFEST_FILE="/etc/odo/manifest.json"
+if [ -e $ODO_MANIFEST_FILE ]; then
+
+  # Retrieving compartmentId from Instance Metadata Service.
+  # Refer: https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.htm
+  COMPARTMENT_ID=$(curl -H "Authorization: Bearer Oracle" -L http://169.254.169.254/opc/v2/instance/compartmentId)
+
+  echo "Using namespace: '$ODO_APPLICATION_ALIAS'\n"
+  echo "Compartment ID set to: $COMPARTMENT_ID\n"
+  chainsaw2 --compartment="$COMPARTMENT_ID" \
+            --namespace="$ODO_APPLICATION_ALIAS"
+
+else
+  echo "Could not find odo manifest file. Exiting."
+  exit 1
+fi
